version: 1
formatters:
  module_func:
    format: "%(asctime)s - %(module)s - %(funcName)s - %(message)s"
    datefmt: "%m-%d %H:%M:%S"
handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    maxBytes: 10485760 # 10MB
    encoding: utf8
    formatter: module_func
    filename: /logs/info.log
loggers:
  timelogger:
    level: DEBUG
    handlers: [file]
    propagate: no
root:
  level: DEBUG
  handlers: [file]
